name: stayv2
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  dart_console: ^4.1.0
  image: ^4.2.0
  meta: ^1.15.0
  uuid: ^4.4.0
  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
